sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
env:
  matrix:
    - DB=postgres TEST=pulp
    - DB=mariadb TEST=pulp
    - DB=postgres TEST=bindings
matrix:
  exclude:
    - python: '3.6'
      env: DB=mariadb TEST=pulp
    - python: '3.7'
      env: DB=postgres TEST=bindings
  fast_finish: true
services:
  - postgresql
  - mariadb
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: '9.6'
  mariadb: '10.3'
before_install: .travis/before_install.sh
install: .travis/install.sh
before_script: .travis/before_script.sh
script:
  - .travis/script.sh
jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: pQVElIk7hM0cyyGz8K+0R23OlcSBocYibi7yOPYUvQ/x8oTEuH/WFt18M5i3YK2tPg3Mypnm+uaUg1vxd+QlJRZTTTj+sSIiGflTkTMIWPpoQ9bm8/oo5MlOP630mK3/Lp117BLAqNJfUm6XW8dikhBFiWZ+IVge3bsuaIOTs+8TNmXT6F0aZZ66RQElcfdllfGSmYv39QzH95XL6d/AgSBh93he26mqlOpHf7gcsT/5UwggW8wDjyF53WYBBuYjg3A7umwHzoilLy98E3ortGF1RaMjlu0jSrlsT+pBdu1ZKwgxEfk3zqKaTYNr/0w9AudsRWMXY8F2oAOG1W5qUoabqiFiVc4AvrP2oZ6q3y1ikv1kLSjGpfmPdz524XY25xoXZOp2M5NIuVo36bZZ9tUhNtkGnE0pufzaRYDAAChWW5xvcOU1ngSDfFkogg4cUmWkVrARBhRwaUcbN2fU/lPDpdaPjg0UCLTCmO8VsGfdvX0NAGu8MUQjbOLvPqzAIR+pEDgKiRIqgW8UlByIAmjh7Z0W8NXLGcTNt2vP9qXnSJpjXP6YU7WlfFEQn9sFwIBQEiCiU2vUfV83iNoVDSaN+0zeeJCHmrY5g/FaqHvXw++vu0ZzK43ZLDy6TU58QP2qooZ6pie8/PGYWVr6U3avXtk/epC3hSHwo6tv1GA=
      on:
        tags: true
    if: tag IS present
  - stage: publish-pulp-file-client-gem
    script: bash .travis/publish_pulp_file_client_gem.sh
    env:
      - DB=postgres
      - TEST=bindings
    if: type != pull_request
